version: '2'
services:
    mia-app:
        image: mia
        external_links:
            - mia-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/mia
        ports:
            - 8080:8080
    mia-postgresql:
        extends:
            file: postgresql.yml
            service: mia-postgresql
